Task 1

In [2]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty array 2x2: \n", empty_array)

ones_array = np.ones((4, 2))
print("\n All-one array 4x2: \n", ones_array)

filled_array = np.full((3, 3), fill_value=7)
print("\n Filled array 3x3 with 7: \n", filled_array)

sample_array = np.array([[5, 6, 7], [8, 9, 10]])
zeros_like_array = np.zeros_like(sample_array)
print("\n Zeros like sample_array: \n", zeros_like_array)

ones_like_array = np.ones_like(sample_array)
print("\n Ones like sample_array: \n", ones_like_array)

new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\n Array from list: \n ", array_from_list)


Empty array 2x2: 
 [[4.08290379e-315 0.00000000e+000]
 [6.59256391e-310 5.76851285e-317]]

 All-one array 4x2: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 Filled array 3x3 with 7: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 Zeros like sample_array: 
 [[0 0 0]
 [0 0 0]]

 Ones like sample_array: 
 [[1 1 1]
 [1 1 1]]

 Array from list: 
  [1 2 3 4]


Task 2

In [4]:
import numpy as np

arr1 = np.arange(10, 50)
print("Array from 10 to 49: \n", arr1)

arr2 = np.arange(9).reshape(3, 3)
print("\n 3x3 matrix 0 to 8: \n", arr2)

identity_matrix = np.eye(3)
print("\n 3x3 Identity matrix: \n", identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n Random array of size 30: \n", random_array)
print("Mean of the array:", mean_value)

random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("\n 10x10 Random array: \n", random_10x10)
print("Min:", min_val, "Max:", max_val)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\n Zero array with 5th element as 1: \n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n Reversed array: \n", reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n 2D array with 1 on border and 0 inside: \n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n 8x8 Checkerboard pattern: \n", checkerboard)


Array from 10 to 49: 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 3x3 matrix 0 to 8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 3x3 Identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Random array of size 30: 
 [0.13870704 0.12346358 0.59500545 0.89003846 0.47896142 0.69626039
 0.56808325 0.39313041 0.37347092 0.06212195 0.42550375 0.66191187
 0.48187988 0.06257553 0.3385008  0.09509331 0.90996073 0.47765971
 0.25042922 0.83895399 0.13436858 0.74925587 0.59041501 0.01845307
 0.61641744 0.41198124 0.3089371  0.34897825 0.65674339 0.88376066]
Mean of the array: 0.4527007424891351

 10x10 Random array: 
 [[0.49168006 0.26831146 0.16670801 0.5970112  0.19220938 0.88979497
  0.54641015 0.32063762 0.30586845 0.99060309]
 [0.37392938 0.48415276 0.79705876 0.3351834  0.71676444 0.27537414
  0.04404484 0.97846787 0.18142075 0.12972779]
 [0.21560026 0.27946426 0.34444939 0.90430654 0.13253008 0.79292106
  0.44323558 0.5

Task 3

In [5]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_xy = x + y
print("x + y: \n", add_xy)

sub_xy = x - y
print("\n x - y: \n", sub_xy)

mult_x = x * 3
print("\n x * 3: \n", mult_x)

square_x = x ** 2
print("\n x squared: \n", square_x)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n Dot product v.w:", dot_vw)
print("Dot product x.v: \n", dot_xv)
print("Dot product x.y: \n", dot_xy)

concat_row = np.concatenate((x, y), axis=0)
concat_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)
print("\n Concatenate x and y along rows: \n", concat_row)
print("\n Concatenate v and w along columns: \n", concat_col)

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv = str(e)
print("\n Attempt to concatenate x and v: \n", concat_xv)


x + y: 
 [[ 6  8]
 [10 13]]

 x - y: 
 [[-4 -4]
 [-4 -3]]

 x * 3: 
 [[ 3  6]
 [ 9 15]]

 x squared: 
 [[ 1  4]
 [ 9 25]]

 Dot product v.w: 219
Dot product x.v: 
 [29 77]
Dot product x.y: 
 [[19 22]
 [50 58]]

 Concatenate x and y along rows: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

 Concatenate v and w along columns: 
 [[ 9 11]
 [10 12]]

 Attempt to concatenate x and v: 
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Task 4

In [6]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A . A^-1 = \n", identity_check)

print("Is close to identity: \n", np.allclose(identity_check, np.eye(2)))

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n 2. AB = \n", AB)
print("BA = \n", BA)
print("Is AB equal to BA?", np.array_equal(AB, BA))

AB_T = (AB).T
BT_AT = np.dot(B.T, A.T)
print("\n 3. (AB)^T = \n", AB_T)
print("B^T . A^T = \n", BT_AT)
print("Is (AB)^T equal to B^T A^T?", np.allclose(AB_T, BT_AT))


A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])

A_eq_inv = np.linalg.inv(A_eq)
X = np.dot(A_eq_inv, B_eq)
print("\n Solution using inverse method: x, y, z = \n", X)

check = np.dot(A_eq, X)
print("Check A*X = B: \n", check)


1. A . A^-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is close to identity: 
 True

 2. AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Is AB equal to BA? False

 3. (AB)^T = 
 [[23 51]
 [13 29]]
B^T . A^T = 
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T? True

 Solution using inverse method: x, y, z = 
 [ 2.  1. -2.]
Check A*X = B: 
 [-1. -3.  9.]
